FROM daocloud.io/gizwits2015/python:latest

MAINTAINER Jam Huang <jamhuang@gizwits.com>

RUN apt-get update
RUN apt-get install -y python-numpy python-scipy
RUN mkdir -p /schedule
RUN mkdir -p /gw_re_processor
COPY deploy/requirement.txt.docker requirements.txt
RUN /usr/bin/pip install -i http://pypi.douban.com/simple/ -r requirements.txt

VOLUME /data/supervisor

COPY . /gw_re_processor
WORKDIR /gw_re_processor
#ADD supervisord.conf.pro supervisord.conf

EXPOSE 80

ENTRYPOINT ["/gw_re_processor/docker-entrypoint.sh"]
